#+TITLE: Xmms Sync
#+AUTHOR: Rémi Vanicat <vanicat@debian.org>

Copyright: (c) 2011, 2012 Rémi Vanicat

* About
  This is a small client for xmms2 that will allow sync a collection
  with a removable media player.

  To run you must first extract the code with emacs an org-mode
  C-c C-v t then copy xmms2-sync somewhere in the path so you can run
  it.

** Some TODO:
*** TODO use ipod specific library
*** TODO build a GUI
*** TODO use a config file.
*** TODO delete first copy after to have the place

** Licence
   :PROPERTIES:
   :ID:       400dffa3-3529-4583-b776-af98d7d5610e
   :END:

   #+name: copyright
   #+begin_src text
     Copyright (c) 2011,2012 Rémi Vanicat

     Permission is hereby granted, free of charge, to any person obtaining a
     copy of this software and associated documentation files (the "Software"),
     to deal in the Software without restriction, including without limitation
     the rights to use, copy, modify, merge, publish, distribute, sublicense,
     and/or sell copies of the Software, and to permit persons to whom the
     Software is furnished to do so, subject to the following conditions:

     The above copyright notice and this permission notice shall be included in
     all copies or substantial portions of the Software.

     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
     IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
     FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
     SOFTWARE IN THE PUBLIC INTEREST, INC. BE LIABLE FOR ANY CLAIM, DAMAGES OR
     OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
     ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
     DEALINGS IN THE SOFTWARE.

     Except as contained in this notice, the name of Rémi Vanicat shall not be
     used in advertising or otherwise to promote the sale, use or other dealings
     in this Software without prior written authorization from Rémi Vanicat.
   #+end_src

* The structure of the program
  :PROPERTIES:
  :ID:       febdc89b-bfbc-4782-bf53-8b19ff298cf4
  :END:
  #+begin_src ruby :tangle xmms2-sync :noweb yes :shebang #!/usr/bin/ruby
    # <<copyright>>

    # This code is wrote using org-mode's babel's litterate programing
    # you should modify xmms2-sync.org, and not xmms2-sync directly.

    <<useful>>

    <<libraries>>

    <<encode>>

    <<xmms-extension>>

    <<server-interaction>>

    <<path-reading>>

    <<sync>>

    <<runing-it>>
  #+end_src

** then included libraries
   :PROPERTIES:
   :ID:       303f4137-59ce-4c9f-810d-00f24548bafa
   :END:
   #+name: libraries
   #+begin_src ruby
     require 'xmmsclient'
     require 'optparse'
     require 'uri'
     require 'pathname'
     require 'fileutils'
   #+end_src

* Path for lesser filesystem
** Encoding name
   #+name: encode_name
   #+begin_src ruby
     def encoding_path(path)
       path=path.to_s
       path=path.gsub(/[<>:\"\\|?*]/,'_')
       path.gsub!(/\.*\//,'/')
       path.encode!("UTF-8","UTF-8") # will fail for filesystem not in utf-8, or
       return path
     end
   #+end_src
** Compare path that could have been encoded
   #+name: compare_name
   #+begin_src ruby
     def compare_path(path1,path2)
       path1 = encoding_path(path1)
       path2 = encoding_path(path2)
       path1.casecmp(path2)
     end
   #+end_src
** structure
   #+name: encode
   #+begin_src ruby :noweb yes
     <<encode_name>>
     <<compare_name>>
   #+end_src

* Some useful function
  #+name: useful
  #+begin_src ruby
    def print_size(size, human)
      if human then
        units = [ 'o', 'Kio', 'Mio', 'Gio', 'Tio', 'Pio', 'Eio', 'Zio', 'Yio' ]
        unit_index = 0
        while size > 1024 and unit_index + 1 < units.length do
          size /= 1024
          unit_index += 1
        end
        return "#{size} #{units[unit_index]}"
      else
        return size.to_s
      end
    end

  #+end_src

* The interaction with the xmms server
** The structure of the class
   :PROPERTIES:
   :ID:       60333ece-ab83-4b09-b474-e04e9ea0606c
   :END:
   #+name: server-interaction
   #+begin_src ruby :noweb yes
     class XmmsInteract
       <<reading-xmms-hash>>

       <<initialization>>

       <<connection-handling>>

       <<reading-server-information>>
     end
   #+end_src

   #+name: reading-xmms-hash
   #+begin_src ruby
     def get(info, attr, default=nil)
       info[attr].map[0][1]
     rescue NoMethodError => e
       default
     end
   #+end_src

** initializing
   :PROPERTIES:
   :ID:       83142473-12ba-40ab-b4d8-9a9169b4db1f
   :END:
   #+name: initialization
   #+begin_src ruby
     def initialize
       unless connect!
         puts 'Failed to connect to XMMS2 daemon.'
         puts 'Please make sure xmms2d is running and using the correct IPC path.'
         exit
       end
     end
   #+end_src

** connection hangling
   :PROPERTIES:
   :ID:       acdc6116-8573-46f2-be35-c706c3d5f5b7
   :END:
   we connect, and reconnect.
   #+name: connection-handling
   #+begin_src ruby
     def connect!
       begin
         @xc = Xmms::Client.new('GtkRater').connect(ENV['XMMS_PATH'])
       rescue Xmms::Client::ClientError
         return false
       end

       @xc.on_disconnect do
         exit
       end

       return true
     end
   #+end_src

** TODO Reading collections
   #+name: reading-server-information
   #+begin_src ruby
     def get_colletion(pattern, options)
       maxsize = options[:size]
       random = options[:random]
       human = options[:human]

       coll = Xmms::Collection.parse(pattern)
       if random then
         order = ['random']          # doesn't work for now...
       else
         order = ['id']
       end
       res = @xc.coll_query_info(coll,['url','size'],order).wait.value

       list = []

       size = 0

       res.each do |song|
         if song[:size] then
           song_path = Pathname(URI.decode(URI(song[:url]).path).gsub(/\+/, ' '))
           if song_path.exist? then
             size += song[:size]
             if maxsize && size > maxsize then
               size -= song[:size]
               break
             end
             list << song_path
           end
         end
       end
       print "size to sync #{print_size(size, human)}\n"
       if (maxsize && ! random && size > maxsize ) then
         print "to much things to sync\n"
         exit(-1)                  #TODO: do not exit for when there is a gui
       end
       if options[:encode] then
         list.sort! do |x,y| compare_path x,y end
       else
         list.sort! do |x,y| x.to_s <=> y.to_s end
       end
       return list
     end
   #+end_src

* Reading a directories
  #+name: path-reading
  #+begin_src ruby
    def find_in_dir path,options
      path=Pathname(path)
      li = []
      path.find do |x|
        li << x
      end
      if options[:encode] then
        li.sort! do |x,y| compare_path(x,y) end
      else
        li.sort! do |x,y| x.to_s <=> y.to_s end
      end
      return li
    end
  #+end_src

* syncing directories
** The syncing structure
   #+name: sync
   #+begin_src ruby
     <<action-only-source>>
     <<action-only-dest>>
     <<action-both>>
     <<syncing-it>>
   #+end_src

** syncing when there is the source and not the dest
   #+name: action-only-source
   #+begin_src ruby
     def action_from_source(sync_dir,dest_dir,song,options)
       source_song=sync_dir + song
       if options[:encode] then
         dest_song=dest_dir + encoding_path(song)
       else
         dest_song=dest_dir + song
       end
       if not(options[:dry_run]) then
         dest_song.dirname.mkpath
       end
       if not(options[:silence]) then
         print("copying #{source_song} to #{dest_song}\n")
       end
       if not(options[:dry_run]) then
         FileUtils.cp(source_song,dest_song)
       end
     end
   #+end_src

** syncing when there is the dest and not the source
   #+name: action-only-dest
   #+begin_src ruby
     def action_from_dest(sync_dir,dest_dir,song,options)
       dest_song=dest_dir + song
       if not(options[:silence]) then
         print("deleting #{dest_song}\n")
       end
       if not(options[:dry_run]) then
         dest_song.unlink
       end
     end
   #+end_src

** syncing when there both
   #+name: action-both
   #+begin_src ruby
     def action_both(sync_dir,dest_dir,song,options)
       # let's do nothing
     end
   #+end_src

** Let's do it
   #+name: syncing-it
   #+begin_src ruby
     def get_song(dir,list)
       song = list.pop
       while song && song.directory?
         song = list.pop
       end
       song && song.relative_path_from(dir)
     end

     def sync(sync_dir,sync_list,dest_dir,dest_list,options)
       dest_song = get_song(dest_dir,dest_list)
       sync_song = get_song(sync_dir,sync_list)
       while dest_song && sync_song
         if options[:encode]
           cmp = compare_path dest_song,sync_song
         else
           cmp = dest_song <=> sync_song
         end

         if cmp > 0
           action_from_dest(sync_dir,dest_dir,dest_song,options)
           dest_song = get_song(dest_dir,dest_list)
         elsif cmp < 0
           action_from_source(sync_dir,dest_dir,sync_song,options)
           sync_song = get_song(sync_dir,sync_list)
         else
           action_both(sync_dir,dest_dir,sync_song,options)
           dest_song = get_song(dest_dir,dest_list)
           sync_song = get_song(sync_dir,sync_list)
         end
       end
       while dest_song
         action_from_dest(sync_dir,dest_dir,dest_song,options)
         dest_song = get_song(dest_dir,dest_list)
       end
       while sync_song
         action_from_source(sync_dir,dest_dir,sync_song,options)
         sync_song = get_song(sync_dir,sync_list)
       end
     end
   #+end_src

* option reading
** Reading the options
   #+name: option-reading
   #+begin_src ruby
     options = {}

     optparse = OptionParser.new do|opts|
       # Set a banner, displayed at the top
       # of the help screen.
       opts.banner = "Usage: xmms2-mp3player-sync [options] sync-from sync-to search-pattern"
       options[:size] = nil
       opts.on('-s', '--size size', 'TODO Size to be sync, in Byte') do |size|
         options[:size] = size.to_i
       end

       options[:random] = false
       opts.on('-r', '--random', 'TODO if collection is too big, choose file to sync at random') do
         options[:random] = true
       end

       opts.on( '-h', '--help', 'Display this screen' ) do
         puts opts
         exit
       end


       options[:dry_run] = false
       opts.on( '-n', '--no-do', 'Do nothing, just print what should be done' ) do
         options[:dry_run] = true
       end

       options[:silence] = false
       opts.on( '-o', '--only-size', 'Do nothing, just print the size of the search' ) do
         options[:silence] = false
         options[:dry_run] = true
       end

       options[:human]=false
       opts.on( '-H', '--human-readable-size', 'When printing size convert to human readable one' ) do
         options[:human]=true
       end

       options[:encode]=false
       opts.on( '-e', '--encode', 'Encode the file name' ) do
         options[:encode]=true
       end
     end

     optparse.parse!

     if ARGV.length < 3 then
       puts(optparse)
       exit(-1)
     end

     syncfrom = ARGV.slice!(0)
     syncto = ARGV.slice!(0)
     pattern = ARGV
   #+end_src

* TODO Connecting the dot, and running all this
  :PROPERTIES:
  :ID:       d7319434-31e9-41b7-a9e4-19759edaaaeb
  :END:
  #+name: runing-it
  #+begin_src ruby :noweb true
    $0 = "xmms2-sync"

    def main ()
      <<option-reading>>

      xc = XmmsInteract.new
      synclist = xc.get_colletion(pattern.join(" "),options)

      destlist = find_in_dir(syncto,options)

      sync(Pathname(syncfrom),synclist,Pathname(syncto),destlist,options)
    end

    main()
  #+end_src
